### ISSUE TITLE
缺失fmdt.dll

### ISSUE THREAD

**Issue by fdsamxn** [LinkClinton/path-tracing-gpu#3]
您好，我编译完这个程序，在跑的时候系统提示缺失fmdt.dll， 您知道是怎么回事吗?

**Comment by LinkClinton** [comment]
如果vcpkg安装了并且安装了需要的第三方库的话，缺少fmtd.dll的话就重新编译整个解决方案应该可以解决。原因是VS会神奇的自动清理掉生成的.dll文件。有空我会看下这个具体啥情况。

**Comment by fdsamxn** [comment]
> 如果vcpkg安装了并且安装了需要的第三方库的话，缺少fmtd.dll的话就重新编译整个解决方案应该可以解决。原因是VS会神奇的自动清理掉生成的.dll文件。有空我会看下这个具体啥情况。

好的，非常感谢您的回答. 我已经用vcpkg安装了需要第三方库，我在试试重新编译一次。
--> 还是出现一样的情况。

**Comment by LinkClinton** [comment]
抱歉没看到-->后面的内容...今天刚准备close的时候才看到。重新编译的时候能盯着项目文件夹里面的bin/x64/xxx/看是否有输出fmtd.dll吗

**Comment by LinkClinton** [comment]
我没有办法在本机复现这个问题，我怀疑可能是vcpkg的安装问题。但是如果有问题应该编译都不可能成功。

**Comment by LinkClinton** [comment]
我更新了下目录结构以及生成。不过我想了想问题可能是杀软导致的。fmtd.dll可能被杀掉了。你可以尝试吧整个项目的文件夹添加到排除项里面去。

**Comment by fdsamxn** [comment]
> 抱歉没看到-->后面的内容...今天刚准备close的时候才看到。重新编译的时候能盯着项目文件夹里面的bin/x64/xxx/看是否有输出fmtd.dll吗

大佬，非常感谢您的回复，现在已经没有缺失fmtd.dll问题了。就是出现了新的问题哈哈哈 -_-, 解析shader的时候，不过没事, 我放弃了, 我看看代码的构架的是怎么样的就行了。非常感谢 :)
